
const UPDATE_BASIC_INFO_add_new_projects = "UPDATE_BASIC_INFO_add_new_projects"

const UPDATE_MEDIA_add_new_projects = "UPDATE_MEDIA_add_new_projects"

export {UPDATE_BASIC_INFO_add_new_projects,UPDATE_MEDIA_add_new_projects}