
//Project Manager
const UPDATE_BASIC_INFO_add_new_projects = "UPDATE_BASIC_INFO_add_new_projects";
const UPDATE_MEDIA_add_new_projects = "UPDATE_MEDIA_add_new_projects";
const ADD_PROJECT_IN_STATIC_LIST_OF_PROJECTS_set_trending_projects = "ADD_PROJECT_IN_STATIC_LIST_OF_PROJECTS_set_trending_projects"; 
const ADD_PROJECT_IN_DYNAMIC_LIST_OF_PROJECTS_set_trending_projects = "ADD_PROJECT_IN_DYNAMIC_LIST_OF_PROJECTS_set_trending_projects"; 

export {UPDATE_BASIC_INFO_add_new_projects,UPDATE_MEDIA_add_new_projects,ADD_PROJECT_IN_STATIC_LIST_OF_PROJECTS_set_trending_projects,ADD_PROJECT_IN_DYNAMIC_LIST_OF_PROJECTS_set_trending_projects}