import React, { useState, useEffect } from "react";
import { Grid, Typography } from "@material-ui/core";
import { makeStyles, withStyles } from "@material-ui/core/styles";
import { ReactIcon } from "../../../Theme/Icons/png/TechnologyIcons";
import { useMediaQuery } from "@material-ui/core";

export default function TechnologyIcons() {
  const isDesktopOrLaptopOrTabletScreen = useMediaQuery("(min-width: 960px)");
  const IconSize = isDesktopOrLaptopOrTabletScreen ? 60 : 40;
  const handleClick = () => {};
  return (
    <Grid
      md={10}
      xs={12}
      sm={12}
      container
      justifyContent="center"
      alignItems="center"
    >
      <Grid
        item
        md={2}
        sm={2}
        xs={3}
        container
        justifyContent="center"
        alignItems="center"
      >
        <ReactIcon
          title="react"
          fontsize={IconSize}
          color="blue"
          handleClick={handleClick}
        />
      </Grid>
      <Grid
        item
        md={2}
        sm={2}
        xs={3}
        container
        justifyContent="center"
        alignItems="center"
      >
        <ReactIcon
          title="react"
          fontsize={IconSize}
          color="blue"
          handleClick={handleClick}
        />
      </Grid>
      <Grid
        item
        md={2}
        sm={2}
        xs={3}
        container
        justifyContent="center"
        alignItems="center"
      >
        <ReactIcon
          title="react"
          fontsize={IconSize}
          color="blue"
          handleClick={handleClick}
        />
      </Grid>
      <Grid
        item
        md={2}
        sm={2}
        xs={3}
        container
        justifyContent="center"
        alignItems="center"
      >
        <ReactIcon
          title="react"
          fontsize={IconSize}
          color="blue"
          handleClick={handleClick}
        />
      </Grid>
      <Grid
        item
        md={2}
        sm={2}
        xs={3}
        container
        justifyContent="center"
        alignItems="center"
      >
        <ReactIcon
          title="react"
          fontsize={IconSize}
          color="blue"
          handleClick={handleClick}
        />
      </Grid>
      <Grid
        item
        md={2}
        sm={2}
        xs={3}
        container
        justifyContent="center"
        alignItems="center"
      >
        <ReactIcon
          title="react"
          fontsize={IconSize}
          color="blue"
          handleClick={handleClick}
        />
      </Grid>
      <Grid
        item
        md={2}
        sm={2}
        xs={3}
        container
        justifyContent="center"
        alignItems="center"
      >
        <ReactIcon
          title="react"
          fontsize={IconSize}
          color="blue"
          handleClick={handleClick}
        />
      </Grid>
      <Grid
        item
        md={2}
        sm={2}
        xs={3}
        container
        justifyContent="center"
        alignItems="center"
      >
        <ReactIcon
          title="react"
          fontsize={IconSize}
          color="blue"
          handleClick={handleClick}
        />
      </Grid>
      <Grid
        item
        md={2}
        sm={2}
        xs={3}
        container
        justifyContent="center"
        alignItems="center"
      >
        <ReactIcon
          title="react"
          fontsize={IconSize}
          color="blue"
          handleClick={handleClick}
        />
      </Grid>
      <Grid
        item
        md={2}
        sm={2}
        xs={3}
        container
        justifyContent="center"
        alignItems="center"
      >
        <ReactIcon
          title="react"
          fontsize={IconSize}
          color="blue"
          handleClick={handleClick}
        />
      </Grid>
      <Grid
        item
        md={2}
        sm={2}
        xs={3}
        container
        justifyContent="center"
        alignItems="center"
      >
        <ReactIcon
          title="react"
          fontsize={IconSize}
          color="blue"
          handleClick={handleClick}
        />
      </Grid>
      <Grid
        item
        md={2}
        sm={2}
        xs={3}
        container
        justifyContent="center"
        alignItems="center"
      >
        <ReactIcon
          title="react"
          fontsize={IconSize}
          color="blue"
          handleClick={handleClick}
        />
      </Grid>
    </Grid>
  );
}
